name: azure-functions-demo
runtime: nodejs
description: Azure Functions infrastructure demo using Pulumi and TypeScript
template:
  config:
    azure-native:location:
      description: The Azure region to deploy to
      default: eastasia